### ISSUE TITLE
Not setting page.st or a theme results to NPE

### ISSUE THREAD

**Issue by eed3si9n** [lightbend/paradox#19]
### steps

Try using without themes

### problem

```
java.lang.NullPointerException
           at com.lightbend.paradox.template.PageTemplate.write(PageTemplate.scala:35)
           at com.lightbend.paradox.ParadoxProcessor.com$lightbend$paradox$ParadoxProcessor$$render$1(ParadoxProcessor.scala:56)
           at com.lightbend.paradox.ParadoxProcessor$$anonfun$process$1.apply(ParadoxProcessor.scala:60)
           at com.lightbend.paradox.ParadoxProcessor$$anonfun$process$1.apply(ParadoxProcessor.scala:60)
           at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
           at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
           at scala.collection.immutable.List.foreach(List.scala:318)
```

https://github.com/lightbend/paradox/blob/master/core/src/main/scala/com/lightbend/paradox/template/PageTemplate.scala#L35

```
templates.getInstanceOf(name) is null
```

### expectation

Display an error message.

**Comment by dwijnand** [comment]
What about if we defaulted the theme? I think that's a better out-the-box experience.
