### ISSUE TITLE
Provide proper error message when reference cannot be resolved

### ISSUE THREAD

**Issue by jrudolph** [lightbend/paradox#33]
Currently, we are getting errors like this:

```
java.util.NoSuchElementException: key not found: ../client-side/index.md#http-client-side-java
	at scala.collection.MapLike$class.default(MapLike.scala:228)
	at scala.collection.AbstractMap.default(Map.scala:58)
	at scala.collection.MapLike$class.apply(MapLike.scala:141)
	at scala.collection.AbstractMap.apply(Map.scala:58)
	at com.lightbend.paradox.markdown.RefDirective.render(Directive.scala:91)
	at com.lightbend.paradox.markdown.DirectiveSerializer.visit(Directive.scala:39)
	at org.pegdown.ToHtmlSerializer.visit(ToHtmlSerializer.java:386)
	at org.pegdown.ast.DirectiveNode.accept(DirectiveNode.java:58)
	at org.pegdown.ToHtmlSerializer.visitChildren(ToHtmlSerializer.java:397)
	at org.pegdown.ToHtmlSerializer.visit(ToHtmlSerializer.java:381)
	at org.pegdown.ast.SuperNode.accept(SuperNode.java:43)
	at org.pegdown.ToHtmlSerializer.visitChildren(ToHtmlSerializer.java:397)
	at org.pegdown.ToHtmlSerializer.printTag(ToHtmlSerializer.java:418)
	at org.pegdown.ToHtmlSerializer.printBreakBeforeTag(ToHtmlSerializer.java:425)
	at org.pegdown.ToHtmlSerializer.visit(ToHtmlSerializer.java:190)
	at org.pegdown.ast.ParaNode.accept(ParaNode.java:35)
	at org.pegdown.ToHtmlSerializer.visitChildren(ToHtmlSerializer.java:397)
	at org.pegdown.ToHtmlSerializer.visit(ToHtmlSerializer.java:89)
	at org.pegdown.ast.RootNode.accept(RootNode.java:51)
	at org.pegdown.ToHtmlSerializer.toHtml(ToHtmlSerializer.java:70)
	at com.lightbend.paradox.markdown.Writer.write(Writer.scala:43)
	at com.lightbend.paradox.ParadoxProcessor$PageContents.<init>(ParadoxProcessor.scala:80)
	at com.lightbend.paradox.ParadoxProcessor.com$lightbend$paradox$ParadoxProcessor$$render$1(ParadoxProcessor.scala:60)
	at com.lightbend.paradox.ParadoxProcessor$$anonfun$process$1.apply(ParadoxProcessor.scala:68)
	at com.lightbend.paradox.ParadoxProcessor$$anonfun$process$1.apply(ParadoxProcessor.scala:68)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:251)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:105)
	at com.lightbend.paradox.ParadoxProcessor.process(ParadoxProcessor.scala:68)
	at com.lightbend.paradox.sbt.ParadoxPlugin$$anonfun$paradoxSettings$25.apply(ParadoxPlugin.scala:94)
	at com.lightbend.paradox.sbt.ParadoxPlugin$$anonfun$paradoxSettings$25.apply(ParadoxPlugin.scala:92)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (docs/compile:paradoxMarkdownToHtml) java.util.NoSuchElementException: key not found: ../client-side/index.md#http-client-side-java
```

Would be nice to know what source and target files and lines are (and maybe even a suggestion what needs to be fixed).

**Comment by jrudolph** [comment]
I think this is actually a bug introduced in 0.2.3 so that ref links cannot be resolved any more.

**Comment by jrudolph** [comment]
The main problem seems to be here that linking to anchors using @ref is not working any more.
