### ISSUE TITLE
RuntimeException: StringTemplate 'page' was not found

### ISSUE THREAD

**Issue by coffius** [lightbend/paradox#373]
I get this error every time when I try to generate documentation using paradox plugin for SBT:

```
[error] java.lang.RuntimeException: StringTemplate 'page' was not found for '/Users/ashamenev/dev/evo/everest-free-game-configurator/public-api-docs/target/site-api/paradox/html/index.html'. Create a template or set a theme that contains one.
[error]         at scala.sys.package$.error(package.scala:26)
[error]         at com.lightbend.paradox.template.PageTemplate.write(PageTemplate.scala:41)
[error]         at com.lightbend.paradox.ParadoxProcessor.render$1(ParadoxProcessor.scala:67)
[error]         at com.lightbend.paradox.ParadoxProcessor.$anonfun$process$6(ParadoxProcessor.scala:71)
[error]         at scala.collection.immutable.List.flatMap(List.scala:334)
[error]         at com.lightbend.paradox.ParadoxProcessor.process(ParadoxProcessor.scala:71)
[error]         at com.lightbend.paradox.sbt.ParadoxPlugin$.$anonfun$paradoxSettings$37(ParadoxPlugin.scala:144)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
```

**Comment by jeschkies** [comment]
I have the same issue. @coffius, how did you solve the issue?
